############### Time ###############
ARG Build_Time
ARG qbitorrent_tag
####################################

FROM ddsderek/qbittorrent_skip_patch:downloader-${Build_Time} AS Build

############### Version ###############
ARG Qbittorrent
ARG Libtorrent
#######################################

COPY choose.sh .

RUN bash choose.sh

FROM nevinee/qbittorrent:${qbitorrent_tag}

COPY --from=Build --chmod=755 /qbittorrent-nox   /usr/bin/qbittorrent-nox
