FROM debian:10.12-slim

RUN apt-get update -y && \
    apt-get install wget bash -y && \
    mkdir /build && \
    cd /build && \
    wget https://raw.githubusercontent.com/ChisBread/qbittorrent_skip_patch/main/qbittorrent-nox-static.sh && \
    bash /build/qbittorrent-nox-static.sh all -i
