FROM alpine:3.16

RUN apk add wget bash && \
    mkdir /build && \
    cd /build && \
    wget https://raw.githubusercontent.com/ChisBread/qbittorrent_skip_patch/main/qbittorrent-nox-static.sh && \
    bash /build/qbittorrent-nox-static.sh all -i
