FROM ubuntu:20.04

ENV qbitorrent_tag=4.3.9
ENV libtorrent_tag=LPE_v0.4

RUN apt-get update -y && \
    apt-get install wget bash -y && \
    mkdir /build && \
    cd /build && \
    wget https://raw.githubusercontent.com/ChisBread/qbittorrent_skip_patch/main/qbittorrent-nox-static.sh && \
    qbitorrent_github_tag=release-${qbitorrent_tag} libtorrent_github_tag=${libtorrent_tag} bash /build/qbittorrent-nox-static.sh all -i
