############### Time ###############
ARG Build_Time=2023-01-30
ARG qbitorrent_tag=4.5.0-iyuu
####################################

FROM ddsderek/qbittorrent_skip_patch:downloader-${Build_Time} AS Build

############### Version ###############
ENV Qbittorrent=4_5_x
ENV Libtorrent=RC_1_2
#######################################

COPY choose.sh .

RUN bash choose.sh

FROM nevinee/qbittorrent:${qbitorrent_tag}

COPY --from=Build --chmod=755 /qbittorrent-nox   /usr/bin/qbittorrent-nox
