name: Downloader qBittorrent

on:
  workflow_dispatch:

jobs:
  build:
    name: Downloader qBittorrent
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        id: date
        run: |
          today=$(date +'%Y-%m-%d')
          echo "today=${today}" >> $GITHUB_OUTPUT
          echo ${today} > versions/Build_Time
          echo "Qbittorrent=$(cat versions/Qbittorrent)" >> $GITHUB_OUTPUT
          echo "Libtorrent=$(cat versions/Libtorrent)" >> $GITHUB_OUTPUT

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "bump: update Build_Time ${today}"
          git push -v --progress

      - 
        name: Buildx
        uses: docker/build-push-action@v3
        with:
          context: Downloader
          file: Downloader/Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
          build-args: |
            Qbittorrent=${{ steps.date.outputs.Qbittorrent }}
            Libtorrent=${{ steps.date.outputs.Libtorrent }}
          push: true
          tags: |
             ${{ secrets.DOCKER_USERNAME }}/qbittorrent_skip_patch:downloader-${{ steps.date.outputs.today }}
